on:
  push:
    branches:
      - master

name: Release Gaze

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download JREs
        run: |
          ./untilted/gradlew --stacktrace --info downloadAndExtractJREs
          chmod -R 777 build/jre
      - name: Setup Git Config
        run: |
          git config --global user.email "ci@gazeplay.net"
          git config --global user.name "GazePlay Automation"
      - name: Run Gradle Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./untilted/gradlew --stacktrace --info release -Prelease.useAutomaticVersion=true
      - name: Get Previous tag
        id: previous-tag
        uses: WyriHaximus/github-action-get-previous-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.previous-tag.outputs.tag }}
          release_name: interAACtionGaze ${{ steps.previous-tag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload Assets to Release
        id: upload-assets
        uses: csexton/release-asset-action@v2
        with:
          release-url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`.
          files: |
            ./untilted/build/distributions/interAACtionGaze-linux.tar.gz
            ./untilted/build/distributions/interAACtionGaze-macos.tar.gz
            ./untilted/build/distributions/interAACtionGaze-noJRE.tar.gz
            ./untilted/build/distributions/interAACtionGaze-noJRE.zip
            ./untilted/build/distributions/interAACtionGaze-windows.zip
            ./untilted/build/distributions/interAACtionGaze-windows-x64-installer.exe
          github-token: ${{ secrets.GITHUB_TOKEN }}